version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: knights_api
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/knights

  mongo:
    image: mongo:5
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
